In [2]:
#!pip3 uninstall xlrd

In [3]:
import pandas as pd
import numpy as np
import sqlite3
import requests

# To plot pretty figures
%matplotlib inline
import matplotlib as mpl
import matplotlib.pyplot as plt
mpl.rc('axes', labelsize=14)
mpl.rc('xtick', labelsize=12)
mpl.rc('ytick', labelsize=12)

In [4]:
xls_path = "data/nombres_por_edad_media.xls"

In [5]:
xl = pd.ExcelFile(xls_path)
sheets_lst = xl.sheet_names
print(sheets_lst)

['Hombres', 'Mujeres']


In [6]:
test_name_df = pd.read_excel(
    xls_path, sheet_name = sheets_lst[1], skiprows = 6)

In [7]:
test_name_df.head(5)

Orden        Nombre  Frecuencia  Edad Media (*)
0      1  MARIA CARMEN      641875            59.5
1      2         MARIA      578124            48.4
2      3        CARMEN      366259            60.5
3      4     ANA MARIA      269814            53.6
4      5   MARIA PILAR      258063            59.4

In [8]:
columns = ["name", "freq", "avg_age"]
test_name_df = test_name_df.drop(columns = ["Orden"])
test_name_df.columns = columns
test_name_df["name"] = test_name_df["name"].str.upper().str.strip()

In [9]:
test_name_df.head()

name    freq  avg_age
0  MARIA CARMEN  641875     59.5
1         MARIA  578124     48.4
2        CARMEN  366259     60.5
3     ANA MARIA  269814     53.6
4   MARIA PILAR  258063     59.4

In [10]:
def load_and_clean_names_xls(gender_str):
    columns = ["name", "freq", "avg_age"]
    if gender_str == 'M':
        sheet_idx = 0
    elif gender_str == 'F':
        sheet_idx = 1
    else:
        sheet_idx = None
    df = pd.read_excel(
        xls_path, sheet_name = sheets_lst[sheet_idx], skiprows = 6)
    df = df.drop(columns = ["Orden"])
    df.columns = columns
    df["name"] = df["name"].str.upper().str.strip()
    return df

In [11]:
female_name_df = load_and_clean_names_xls("F")
male_name_df = load_and_clean_names_xls("M")

In [12]:
female_name_df.head()

name    freq  avg_age
0  MARIA CARMEN  641875     59.5
1         MARIA  578124     48.4
2        CARMEN  366259     60.5
3     ANA MARIA  269814     53.6
4   MARIA PILAR  258063     59.4

In [13]:
male_name_df.head()

name    freq  avg_age
0    ANTONIO  640854     57.1
1     MANUEL  562798     55.7
2       JOSE  547142     62.1
3  FRANCISCO  467933     58.7
4      DAVID  369633     32.9

In [14]:
male_name_df[male_name_df["name"].str.contains("GUSTAVO")]

name   freq  avg_age
210             GUSTAVO  12785     43.9
458      GUSTAVO ADOLFO   4101     44.0
1201     CARLOS GUSTAVO   1056     44.2
2362       LUIS GUSTAVO    416     37.6
2404    GUSTAVO ALBERTO    404     47.2
...                 ...    ...      ...
26387     GUSTAVO ELIAS     20     38.9
26388  GUSTAVO HUMBERTO     20     48.1
26421      HUGO GUSTAVO     20     36.4
26640     LUCAS GUSTAVO     20     28.1
26752    NESTOR GUSTAVO     20     48.9

[140 rows x 3 columns]

In [15]:
name_df = pd.merge(
    female_name_df.set_index("name"), 
    male_name_df.set_index("name"), 
    on = ["name"],  
    how = "outer",
    suffixes=('_f', '_m'))

In [16]:
name_df.head()

freq_f  avg_age_f  freq_m  avg_age_m
name                                                
MARIA CARMEN  641875.0       59.5     NaN        NaN
MARIA         578124.0       48.4   183.0       55.4
CARMEN        366259.0       60.5     NaN        NaN
ANA MARIA     269814.0       53.6     NaN        NaN
MARIA PILAR   258063.0       59.4     NaN        NaN

In [17]:
name_df["freq_f"] = name_df["freq_f"].fillna(0)
name_df["freq_m"] = name_df["freq_m"].fillna(0)
name_df["prob_f"] = name_df["freq_f"] / (name_df["freq_f"] + name_df["freq_m"])
name_df["prob_m"] = name_df["freq_m"] / (name_df["freq_f"] + name_df["freq_m"])
name_df["gender"] = np.where(name_df["prob_f"] >= 0.5, "F", "M")

In [18]:
name_df[(name_df["gender"] == "F")].sort_values(["prob_m"], ascending = False).head(5)

freq_f  avg_age_f  freq_m  avg_age_m  prob_f  prob_m gender
name                                                                 
XIAOYANG    21.0       39.9    21.0       27.0     0.5     0.5      F
WISAM       55.0       15.3    55.0       16.0     0.5     0.5      F
ERI         22.0       33.0    22.0       24.4     0.5     0.5      F
MANJEET     55.0       40.0    55.0       37.7     0.5     0.5      F
SHU         31.0       30.4    31.0       33.9     0.5     0.5      F

In [19]:
name_basics_df = name_df[["prob_f", "prob_m", "gender"]]

In [20]:
name_basics_df.sample(5)

prob_f  prob_m gender
name                                 
PATRICIA BELEN     1.0     0.0      F
MARIA VILLA        1.0     0.0      F
IONUT MIHAI        0.0     1.0      M
GABRIEL COSMIN     0.0     1.0      M
RODRIGO JESUS      0.0     1.0      M

In [ ]:
name_basics_df.to_csv("data/names_master.csv")

In [ ]:
#!pip3 install django djangorestframework markdown django-filter

In [ ]:
#!python3 -m django --version

4.0.6


In [ ]:
#!django-admin startproject 

In [ ]:
#!python3 manage.py runserver 0.0.0.0:8000

In [ ]:
#!python manage.py startapp 

In [ ]:
sqliteConnection = sqlite3.connect('db.sqlite3')
cursor = sqliteConnection.cursor()

sqlite_select_Query = """
    SELECT name
    FROM sqlite_master
    WHERE type ='table';
"""
cursor.execute(sqlite_select_Query)
record = cursor.fetchall()
for r in record:
    print(r)
cursor.close()

('django_migrations',)
('sqlite_sequence',)
('auth_group_permissions',)
('auth_user_groups',)
('auth_user_user_permissions',)
('django_admin_log',)
('django_content_type',)
('auth_permission',)
('auth_group',)
('auth_user',)
('django_session',)
('web_name',)


In [ ]:
cursor = sqliteConnection.cursor()
sqlite_select_Query = """
    PRAGMA table_info([web_name]);
"""
cursor.execute(sqlite_select_Query)
record = cursor.fetchall()
for r in record:
    print(r)
cursor.close()

(0, 'id', 'integer', 1, None, 1)
(1, 'text', 'varchar(255)', 1, None, 0)
(2, 'prob_f', 'real', 1, None, 0)
(3, 'prob_m', 'real', 1, None, 0)
(4, 'gender', 'varchar(255)', 1, None, 0)
(5, 'pub_date', 'datetime', 0, None, 0)


In [ ]:
cursor = sqliteConnection.cursor()
sqlite_select_Query = """
    SELECT * 
    FROM web_name
    LIMIT 5;
"""
cursor.execute(sqlite_select_Query)
record = cursor.fetchall()
for r in record:
    print(r)
cursor.close()

(36580, 'MARIA CARMEN', 1.0, 0.0, 'F', None)
(36581, 'MARIA', 0.9996835590784825, 0.0003164409215174639, 'F', None)
(36582, 'CARMEN', 1.0, 0.0, 'F', None)
(36583, 'ANA MARIA', 1.0, 0.0, 'F', None)
(36584, 'MARIA PILAR', 1.0, 0.0, 'F', None)


In [ ]:
cursor = sqliteConnection.cursor()

for index, row in name_basics_df.reset_index().iterrows():
    name = str(row["name"]).replace("'", " ")  
    prob_f = row["prob_f"]
    prob_m = row["prob_m"]
    gender = row["gender"]    

    insert_into_name = """
        INSERT INTO web_name 
            (text, prob_f, prob_m, gender)
            VALUES ('{0}', {1}, {2}, '{3}');
        """.format(name, prob_f, prob_m, gender) 
    if index == 0:
        print("Example query:")
        print(insert_into_name)
    try:
        cursor.execute(insert_into_name)
    except:
        print(insert_into_name)
    sqliteConnection.commit()  

cursor.close()

Example query:

        INSERT INTO web_name 
            (text, prob_f, prob_m, gender)
            VALUES ('MARIA CARMEN', 1.0, 0.0, 'F');
        


In [ ]:
cursor = sqliteConnection.cursor()
sqlite_select_Query = """
    SELECT * 
    FROM web_name;
"""
cursor.execute(sqlite_select_Query)
record = cursor.fetchall()
for r in record:
    print(r)
cursor.close()

(91625, 'MARIA CARMEN', 1.0, 0.0, 'F', None)
(91626, 'MARIA', 0.9996835590784825, 0.0003164409215174639, 'F', None)
(91627, 'CARMEN', 1.0, 0.0, 'F', None)
(91628, 'ANA MARIA', 1.0, 0.0, 'F', None)
(91629, 'MARIA PILAR', 1.0, 0.0, 'F', None)
(91630, 'LAURA', 1.0, 0.0, 'F', None)
(91631, 'JOSEFA', 1.0, 0.0, 'F', None)
(91632, 'ISABEL', 1.0, 0.0, 'F', None)
(91633, 'MARIA DOLORES', 1.0, 0.0, 'F', None)
(91634, 'MARIA TERESA', 1.0, 0.0, 'F', None)
(91635, 'ANA', 1.0, 0.0, 'F', None)
(91636, 'MARTA', 1.0, 0.0, 'F', None)
(91637, 'CRISTINA', 1.0, 0.0, 'F', None)
(91638, 'MARIA ANGELES', 1.0, 0.0, 'F', None)
(91639, 'LUCIA', 1.0, 0.0, 'F', None)
(91640, 'MARIA ISABEL', 1.0, 0.0, 'F', None)
(91641, 'MARIA JOSE', 1.0, 0.0, 'F', None)
(91642, 'FRANCISCA', 1.0, 0.0, 'F', None)
(91643, 'ANTONIA', 1.0, 0.0, 'F', None)
(91644, 'DOLORES', 0.9998785878665128, 0.00012141213348712204, 'F', None)
(91645, 'SARA', 0.9997927091190714, 0.00020729088092866313, 'F', None)
(91646, 'PAULA', 1.0, 0.0, 'F', None)


In [ ]:
#response = requests.get("http://127.0.0.1:8080/api/names/LUIS/")

In [ ]:
#r.status_code

In [ ]:
#print(r.text)

In [21]:
name_basics_w_df = name_basics_df

In [22]:
name_basics_w_df = name_basics_w_df.reset_index()

In [23]:
name_basics_w_df["lword"] = name_basics_w_df["name"].str[-1:]
name_basics_w_df["fword"] = name_basics_w_df["name"].str[:1]

In [24]:
name_basics_w_df.head()

name    prob_f    prob_m gender lword fword
0  MARIA CARMEN  1.000000  0.000000      F     N     M
1         MARIA  0.999684  0.000316      F     A     M
2        CARMEN  1.000000  0.000000      F     N     C
3     ANA MARIA  1.000000  0.000000      F     A     A
4   MARIA PILAR  1.000000  0.000000      F     R     M

In [25]:
name_basics_w_df = name_basics_w_df[
    name_basics_w_df["lword"].notnull()
]
name_basics_w_df = name_basics_w_df[
    name_basics_w_df["fword"].notnull()
]

In [26]:
def is_vowel(word):
    if word.lower() in "aeiou":
        return 1
    return 0

name_basics_w_df["lvowel"] = name_basics_w_df["lword"].apply(is_vowel)
name_basics_w_df["fvowel"] = name_basics_w_df["fword"].apply(is_vowel)

In [27]:
name_basics_w_df.head(10)

name    prob_f    prob_m gender lword fword  lvowel  fvowel
0   MARIA CARMEN  1.000000  0.000000      F     N     M       0       0
1          MARIA  0.999684  0.000316      F     A     M       1       0
2         CARMEN  1.000000  0.000000      F     N     C       0       0
3      ANA MARIA  1.000000  0.000000      F     A     A       1       1
4    MARIA PILAR  1.000000  0.000000      F     R     M       0       0
5          LAURA  1.000000  0.000000      F     A     L       1       0
6         JOSEFA  1.000000  0.000000      F     A     J       1       0
7         ISABEL  1.000000  0.000000      F     L     I       0       1
8  MARIA DOLORES  1.000000  0.000000      F     S     M       0       0
9   MARIA TERESA  1.000000  0.000000      F     A     M       1       0

In [28]:
def count_words(name):
    l = len(name.split(" "))   
    return l

name_basics_w_df["num_words"] = \
    name_basics_w_df["name"].apply(count_words)

In [29]:
name_basics_w_df.head()

name    prob_f    prob_m gender lword fword  lvowel  fvowel  \
0  MARIA CARMEN  1.000000  0.000000      F     N     M       0       0   
1         MARIA  0.999684  0.000316      F     A     M       1       0   
2        CARMEN  1.000000  0.000000      F     N     C       0       0   
3     ANA MARIA  1.000000  0.000000      F     A     A       1       1   
4   MARIA PILAR  1.000000  0.000000      F     R     M       0       0   

   num_words  
0          2  
1          1  
2          1  
3          2  
4          2

In [30]:
def count_chars(name):
    l = len(name)   
    return l

name_basics_w_df["num_chars"] = \
    name_basics_w_df["name"].apply(count_chars)

In [31]:
name_basics_w_df = name_basics_w_df.drop(
    columns = ["prob_f", "prob_m"], 
    axis = 1
)

name_basics_w_df.head()

name gender lword fword  lvowel  fvowel  num_words  num_chars
0  MARIA CARMEN      F     N     M       0       0          2         12
1         MARIA      F     A     M       1       0          1          5
2        CARMEN      F     N     C       0       0          1          6
3     ANA MARIA      F     A     A       1       1          2          9
4   MARIA PILAR      F     R     M       0       0          2         11

In [32]:
from sklearn.preprocessing import OneHotEncoder

In [33]:
from sklearn.preprocessing import OneHotEncoder

enc = OneHotEncoder(
    categories = 'auto',  # Categories per feature
    drop = None, # Whether to drop one of the features
    sparse = True, # Will return sparse matrix if set True
#    dtype = <class 'numpy.float64'>, # Desired data type of the output
    handle_unknown = 'error' # Whether to raise an error 
)       

In [34]:
lword_tr = enc.fit_transform(name_basics_w_df[['lword']])
print(lword_tr.toarray())
#print(lword_tr)

[[0. 0. 0. ... 0. 0. 0.]
 [1. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [35]:
print(enc.categories_)

[array(['A', 'B', 'C', 'D', 'E', 'F', 'G', 'H', 'I', 'J', 'K', 'L', 'M',
       'N', 'O', 'P', 'Q', 'R', 'S', 'T', 'U', 'V', 'W', 'X', 'Y', 'Z',
       'Ç'], dtype=object)]


In [36]:
name_basics_w_df["L_" + enc.categories_[0]] = lword_tr.toarray()

In [37]:
name_basics_w_df.head()

name gender lword fword  lvowel  fvowel  num_words  num_chars  L_A  \
0  MARIA CARMEN      F     N     M       0       0          2         12  0.0   
1         MARIA      F     A     M       1       0          1          5  1.0   
2        CARMEN      F     N     C       0       0          1          6  0.0   
3     ANA MARIA      F     A     A       1       1          2          9  1.0   
4   MARIA PILAR      F     R     M       0       0          2         11  0.0   

   L_B  ...  L_R  L_S  L_T  L_U  L_V  L_W  L_X  L_Y  L_Z  L_Ç  
0  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  ...  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  ...  1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[5 rows x 35 columns]

In [38]:
fword_tr = enc.fit_transform(name_basics_w_df[['fword']])
name_basics_w_df["F_" + enc.categories_[0]] = fword_tr.toarray()

In [39]:
name_basics_w_df["gender"] = np.where(
    name_basics_w_df["gender"] == 'F', 1, 0)
name_basics_w_df = name_basics_w_df.drop(columns = \
    ["lword", "fword", "name"], axis = 1)

In [40]:
name_basics_w_df.head(10)

gender  lvowel  fvowel  num_words  num_chars  L_A  L_B  L_C  L_D  L_E  ...  \
0       1       0       0          2         12  0.0  0.0  0.0  0.0  0.0  ...   
1       1       1       0          1          5  1.0  0.0  0.0  0.0  0.0  ...   
2       1       0       0          1          6  0.0  0.0  0.0  0.0  0.0  ...   
3       1       1       1          2          9  1.0  0.0  0.0  0.0  0.0  ...   
4       1       0       0          2         11  0.0  0.0  0.0  0.0  0.0  ...   
5       1       1       0          1          5  1.0  0.0  0.0  0.0  0.0  ...   
6       1       1       0          1          6  1.0  0.0  0.0  0.0  0.0  ...   
7       1       0       1          1          6  0.0  0.0  0.0  0.0  0.0  ...   
8       1       0       0          2         13  0.0  0.0  0.0  0.0  0.0  ...   
9       1       1       0          2         12  1.0  0.0  0.0  0.0  0.0  ...   

   F_Q  F_R  F_S  F_T  F_U  F_V  F_W  F_X  F_Y  F_Z  
0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
1  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
2  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
3  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
4  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
5  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
6  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
7  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
8  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  
9  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  

[10 rows x 58 columns]

In [41]:
#X = name_basics_w_df[["lvowel", "fvowel", "num_words", "num_chars"]]
X = name_basics_w_df.drop(columns = ["gender"])
y = name_basics_w_df[["gender"]]

In [42]:
from sklearn.tree import DecisionTreeClassifier # Import Decision Tree Classifier
from sklearn.model_selection import train_test_split # Import train_test_split function
from sklearn import metrics 

In [75]:
# Split dataset into training set and test set
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size = 0.2, random_state = 42) # 80% training and 20% test

In [76]:
# Create Decision Tree classifer object
#clf = DecisionTreeClassifier(max_depth = 4)
clf = DecisionTreeClassifier(random_state = 42)

# Train Decision Tree Classifer
clf = clf.fit(X_train,y_train)

#Predict the response for test dataset
y_pred = clf.predict(X_test)

In [77]:
#y_pred

In [78]:
# Model Accuracy, how often is the classifier correct?
print("Accuracy:", metrics.accuracy_score(y_test, y_pred))
print("Jaccard Accuracy:", metrics.jaccard_score(y_test, y_pred))

Accuracy: 0.8143662753073865
Jaccard Accuracy: 0.6761812610869214


In [79]:
from sklearn.model_selection import cross_validate

cv_dict = cross_validate(clf, X, y, return_train_score = True)
cv_dict

{'fit_time': array([0.916188  , 0.86079931, 0.90064406, 0.93062854, 0.84471774]),
 'score_time': array([0.02274036, 0.024616  , 0.02477455, 0.02854919, 0.02453113]),
 'test_score': array([0.81778682, 0.81455117, 0.81092825, 0.81629068, 0.80898669]),
 'train_score': array([0.85110366, 0.85175084, 0.8530717 , 0.85203162, 0.85251699])}

In [82]:
def predict_name(name):
    cols = X.columns.to_list()
    lst = [0] * len(cols)
    #name = "MARIO ANTONIO JESUS"
    last = name[-1:]
    last_str = "L_" + last
    first = name[:1]
    first_str = "F_" + last    
    last_idx = cols.index(last_str)
    if last_idx >= 0:
        lst[last_idx] = 1
    first_idx = cols.index(first_str)
    if first_idx >= 0:
        lst[first_idx] = 1
    lword = is_vowel(last)
    fword = is_vowel(first)
    num_words = count_words(name)
    num_chars = count_chars(name)
    lst[0] = lword
    lst[1] = fword
    lst[2] = num_words
    lst[3] = num_chars           
    d = np.array(lst).reshape(1, -1)
#    e = pd.DataFrame(data = d, columns = cols)
    p = clf.predict(d)
#    p = clf.predict(e)
    print(p)
    if p[0] == 1:
        return "FEMALE"
    else:
        return "MALE"

In [99]:
g = predict_name("GUILLERMO JONATHAN")
print(g)

[1]
FEMALE


/home/personal/.local/lib/python3.8/site-packages/sklearn/base.py:450: UserWarning: X does not have valid feature names, but DecisionTreeClassifier was fitted with feature names
  warnings.warn(


In [100]:
#from sklearn import tree

#plt.figure(figsize=(40,40))
#tree.plot_tree(
#    clf, feature_names = X.columns.to_list(),
#    class_names = ["Male", "Female"],
#    filled = True);

# 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

In [104]:
import pickle
filename = "model_pickle.sav"
pickle.dump(clf, open(filename, 'wb')) 
mod = pickle.load(open(filename, 'rb'))

In [110]:
#mod.feature_importances_

In [113]:
import joblib
filename = "model_joblib.sav"
joblib.dump(clf, filename) 
mod = joblib.load(filename)